### ISSUE TITLE
Wrong formatting with some symbols like ⚠

### ISSUE THREAD

**Issue by andrei200287** [kean/Formatting#3]
Great lib. Thanks!

```swift
let input = "⚠ Example of wrong <t>text format</t>"
let style = FormattedStringStyle(attributes: [
    "t": [.foregroundColor: UIColor.red]
])
self.messageLabel.attributedText = NSAttributedString(formatting: input, style: style)
```

<img width="208" alt="FormattingBug" src="https://user-images.githubusercontent.com/837480/115530445-72d39980-a29c-11eb-81ed-5957449d89c7.png">

**Comment by kean** [comment]
It looks like I broke the indexing when fixing the problem mutation and `String.Index` https://github.com/kean/Formatting/issues/1

**Comment by kean** [comment]
Hey, I tested this code on iOS and it works fine. Are you using the latest Formatting version? What platform are you testing it on?

**Comment by andrei200287** [comment]
> Hey, I tested this code on iOS and it works fine. Are you using the latest Formatting version? What platform are you testing it on?

Sorry for late answer. I use Swift package manager, version 0.0.1. It is old version. Probably need release a new version.

**Comment by kean** [comment]
Pushed a [new version](https://github.com/kean/Formatting/releases/tag/0.1.0), please try it.

**Comment by andrei200287** [comment]
It works, thanks.

**Comment by andrei200287** [comment]
Hello. testEmoji fail with different emoji.
<img width="999" alt="testEmojiFail" src="https://user-images.githubusercontent.com/837480/161297704-2dd3ea5c-ae84-49f0-98e5-b01b3fb020b0.png">

**Comment by kean** [comment]
Yes, something is still not right with indexing.

```
(lldb) po "⚠".unicodeScalars.count
1

(lldb) po "⚠️".unicodeScalars.count
2
```

**Comment by kean** [comment]
Should now be fixed https://github.com/kean/Formatting/releases/tag/0.1.1
