### ISSUE TITLE
SPM is not working (Formatting could not be resolved)

### ISSUE THREAD

**Issue by CavalcanteLeo** [kean/Formatting#5]
<img width="1506" alt="Screen Shot 2022-07-12 at 12 58 55" src="https://user-images.githubusercontent.com/1735944/178538361-bff7a324-79d4-4b85-b5d2-25618aa5e126.png">

**Comment by kean** [comment]
I think it's something on your end. It works for me. Any luck fixing it yet?

**Comment by CavalcanteLeo** [comment]
since I was in a hurry to check if Formatting would work for my needs, i just copied https://github.com/kean/Formatting/blob/master/Source/Formatting.swift

But i will look into it this weekend, and add it to my project the right way
