### ISSUE TITLE
Feature request: onClick

### ISSUE THREAD

**Issue by CavalcanteLeo** [kean/Formatting#6]
Would be amazing if we could detect a click on a word

the same way we map attributes, but to map clicks:

```swift
let onClick = FormattedStringOnClick: attribute in {
	//here we can do any logic we want... something like:
	
	// since the attribute is the whole tag:
	switch tag.tagName {
	"a" {
		// <a href="example"> then we can get the value of href like `attribute.href`
		print(tag.attributes.href) // => output example
		break
	}
	"b": functionB()
	}
}


//extend any Label to support onClick
myLabel.registerOnClick = onClick
```

**Comment by kean** [comment]
If I understand correctly, that's something that you can do relatively easily using `UITextView`: https://stackoverflow.com/a/25466154/1486308

**Comment by CavalcanteLeo** [comment]
would be more like what [Atributika](https://github.com/psharanda/Atributika) and [TTTAttributedLabel](https://github.com/TTTAttributedLabel/TTTAttributedLabel) do

**Comment by kean** [comment]
[Atributika](https://github.com/psharanda/Atributika) looks pretty good. Are there any particular reasons you prefer to use Formatting instead of it? Formatting is primarily just a sample code for [this post](https://kean.blog/post/formatted-strings). I have no plans to extend it at the moment.

**Comment by kean** [comment]
Not sure why it has [a custom parser](https://github.com/psharanda/Atributika/blob/d018897afbd55d9065ef859650585bac890ada7e/Sources/String%2BDetection.swift#L116) instead of an XML scanner though.

**Comment by CavalcanteLeo** [comment]
> [Atributika](https://github.com/psharanda/Atributika) looks pretty good. Are there any particular reasons you prefer to use Formatting instead of it? Formatting is primarily just a sample code for [this post](https://kean.blog/post/formatted-strings). I have no plans to extend it at the moment.

actually no, basically I discovered Formatting first

btw, i found u from Pulse repo, then i looked all ur projects

and in the past i already have used Nuke, but didn't know it was created by u

**Comment by kean** [comment]
That's awesome. So yeah, consider it a sample code. I released it as a package just in case someone would like to use it as is. I do use it myself in production. But I don't plan to work on it or extend it. There are existing frameworks with more features – I suggest using them instead.
